version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Grouping is also recommended to prevent Python dependency update PRs from flooding
    groups:
      python-dependencies:
        patterns:
          - "*"