"""海啸领域辅助能力。"""

from .jma_tsunami_normalize import (
    GRADE_ORDER,
    GRADE_TITLE_MAP,
    build_jma_tsunami_content_fingerprint,
    coerce_bool,
    normalize_jma_tsunami_areas,
    resolve_jma_tsunami_max_grade,
    resolve_jma_tsunami_title,
)
from .tsunami_levels import (
    CN_TSUNAMI_LEVEL_ORDER,
    JP_TSUNAMI_LEVEL_DISPLAY,
    JP_TSUNAMI_LEVEL_ORDER,
    build_tsunami_weather_detail,
    cn_tsunami_level_weight,
    jp_tsunami_level_weight,
    normalize_cn_tsunami_level,
    normalize_jp_tsunami_level,
    resolve_tsunami_region,
    to_optional_float,
)
from .tsunami_title import (
    build_tsunami_list_title,
    build_tsunami_list_title_from_mapping,
    format_tsunami_batch_token,
    format_tsunami_level_label,
    format_tsunami_magnitude_token,
    is_generic_tsunami_title,
    is_legacy_tsunami_description,
    parse_tsunami_batch_num,
)

__all__ = [
    "CN_TSUNAMI_LEVEL_ORDER",
    "GRADE_ORDER",
    "GRADE_TITLE_MAP",
    "JP_TSUNAMI_LEVEL_DISPLAY",
    "JP_TSUNAMI_LEVEL_ORDER",
    "build_jma_tsunami_content_fingerprint",
    "build_tsunami_list_title",
    "build_tsunami_list_title_from_mapping",
    "build_tsunami_weather_detail",
    "cn_tsunami_level_weight",
    "coerce_bool",
    "format_tsunami_batch_token",
    "format_tsunami_level_label",
    "format_tsunami_magnitude_token",
    "is_generic_tsunami_title",
    "is_legacy_tsunami_description",
    "jp_tsunami_level_weight",
    "parse_tsunami_batch_num",
    "normalize_cn_tsunami_level",
    "normalize_jp_tsunami_level",
    "normalize_jma_tsunami_areas",
    "resolve_jma_tsunami_max_grade",
    "resolve_jma_tsunami_title",
    "resolve_tsunami_region",
    "to_optional_float",
]
